# Comment to a new issue.
issueOpened: >
  Thanks for opening an issue! We will try and get back to you as soon as possible. 
  
  Please make sure that you followed the issue template, and provied all the neccessary information.
  Failure to do so may inhibit our ability to resolve the issue.
  
  Please note that suggestions are now to be submitted to https://git.io/fN5B4 rather than this issue tracker!

pullRequestOpened: >
  Thank your for creating your pull request.

  Please make sure you have followed our contribution guidelines and ensured the submitted code is functional. Please note
  that we use different branches to target different Minecraft version.
  
  We will review it as soon as possible!
